"""
Problem 12 - Highly Divisible Triangular Number

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
Let us list the factors of the first seven triangle numbers:
 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.
What is the value of the first triangle number to have over five hundred divisors?"""

import math


def run():

    i = 0
    triangle_num = 0
    longest = 0

    while True:
        triangle_num += i
        num_divisors = get_num_divisors(triangle_num)
        longest = max(longest, num_divisors)
        print(
            f'i: {i}, number: {triangle_num}, divisors: {num_divisors}, longest: {longest}')

        if num_divisors > 500:
            return triangle_num
        i += 1


def get_num_divisors(n):
    """
    Finds divisors of a number, n in O(sqrt(n)) time
    # https://www.geeksforgeeks.org/find-divisors-natural-number-set-1/
    """
    num_divisors = 0
    i = 1
    while (i <= math.sqrt(n)):
        if n % i == 0:
            if n / i == i:
                num_divisors += 1
            else:
                num_divisors += 2
        i += 1

    return num_divisors


if __name__ == "__main__":
    print(run())
