
"""
Problem 45 - Triangular, Pentagonal, Hexagonal

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""

import math

def run():
    n = 40756
    while True:
        if is_triangular(n) and is_pentagonal(n) and is_hexagonal(n):
            return n
        else:
            n+=1
        


def is_triangular(n):
    if (n < 0):
        return False

    # Considering the equation n*(n+1)/2 = num
    # The equation is : a(n^2) + bn + c = 0
    c = (-2 * n)
    b, a = 1, 1
    d = (b * b) - (4 * a * c)

    if (d < 0):
        return False

    # Find roots of equation
    root1 = (-b + math.sqrt(d)) / (2 * a)
    root2 = (-b - math.sqrt(d)) / (2 * a)

    # checking if root1 is natural
    if (root1 > 0 and math.floor(root1) == root1):
        return True

    # checking if root2 is natural
    if (root2 > 0 and math.floor(root2) == root2):
        return True

    return False

def is_pentagonal(n):
    n = (1 + math.sqrt(24 * n + 1)) / 6
    return( (n - int (n)) == 0)

def is_hexagonal(n):
     
    val = 8 * n + 1
    x = 1 + math.sqrt(val)
 
    # Calculate the value for n
    n = x / 4
 
    # Check if n - floor(n)
    # is equal to 0
    if ((n - int(n)) == 0):
        return True
    else:
        return False

if __name__ == "__main__":
    print(run())